Traceback (most recent call last):
  File "/home/wilker/Documentos/Projetos/import/aplicacao.py", line 13, in <module>
    main()
  File "/home/wilker/Documentos/Projetos/import/aplicacao.py", line 6, in main
    cpfs = get_filtered_cpfs()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wilker/Documentos/Projetos/import/google_api.py", line 20, in get_filtered_cpfs
    creds.refresh(Request())
  File "/home/wilker/Documentos/Projetos/import/.venv/lib/python3.12/site-packages/google/oauth2/credentials.py", line 431, in refresh
    ) = reauth.refresh_grant(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wilker/Documentos/Projetos/import/.venv/lib/python3.12/site-packages/google/oauth2/reauth.py", line 366, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/home/wilker/Documentos/Projetos/import/.venv/lib/python3.12/site-packages/google/oauth2/_client.py", line 68, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})
